on: [push]
jobs:
  publish-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/chechout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Docker Image 
        run: |
          docker build -t ghcr.io/alissontresp/exemplo-gha .
          docker push ghcr.io/alissontresp/exemplo-gha